version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    open-pull-requests-limit: 99
    reviewers:
      - "WikiRik"
  - package-ecosystem: "docker"
    directory: "/docker/core"
    schedule:
      interval: "weekly"
      day: "friday"
    open-pull-requests-limit: 99
    reviewers:
      - "WikiRik"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    open-pull-requests-limit: 99
    reviewers:
      - "WikiRik"
