version: "3.4"

services:
    postgres-core:
        restart: always
        image: postgres:10.21
        volumes:
            - postgres-core:/var/lib/postgresql/data
        expose:
            - "5432"
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "${PW_POSTGRES}"

    core:
        restart: always
        image: aegee/core:latest
        volumes:
            - core-media:/usr/app/media
            - shared:/usr/app/shared:ro
            - core-state:/usr/app/src/state:rw
        depends_on:
            - postgres-core
        expose:
            - "8084"
        environment:
            BUGSNAG_KEY: "${BUGSNAG_KEY_CORE}"
            PG_PASSWORD: "${PW_POSTGRES}"
            NODE_ENV: "${MYAEGEE_ENV}"
            HOST: "${SUBDOMAIN_FRONTEND}${BASE_URL}"
            CORE_LOGIN: "${CORE_LOGIN}"
            CORE_PASSWORD: "${CORE_PASSWORD}"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8084/healthcheck"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        labels:
            - "traefik.backend=core"
            - "traefik.port=8084"
            - "traefik.auth.frontend.rule=PathPrefix:/api/core/metrics;PathPrefixStrip:/api/core;"
            - "traefik.old.frontend.rule=PathPrefixStrip:/services/oms-core-elixir/api;"
            - "traefik.new.frontend.rule=PathPrefixStrip:/api/core;"
            - "traefik.auth.frontend.auth.basic.users=admin:${METRICS_CREDENTIALS}"
            - "traefik.old.frontend.priority=110"
            - "traefik.new.frontend.priority=110"
            - "traefik.auth.frontend.priority=120"
            - "traefik.enable=true"

volumes:
    postgres-core:
        driver: local
    core-media:
        driver: local
    shared:
        driver: local
    core-state:
        driver: local

networks:
    default:
        external:
            name: OMS
